# Week 2 Exercises


install.packages("dplyr")

install.packages("ggplot2")

install.packages("GGally")

library(dplyr)

library(ggplot2)

library(GGally)

## 1. Reading the data and describing it
analysisData <- read.table('data/learning2014')
summary(analysisData$Points)

"This data is collected from the social science students of the Univeristy of Helsinki. The survey was conducted in a social sciences statistical course for bachelor students in 2014 December to 2015 January. The survey consists of 7 variables that describe the gender (factored as female or male), age, attitude (towards the study of statistics), deep learning (pupils own attitudes and practices towards deep learning), surface learning and strategic learning as well as their received points in the final exam of the course. The learning scales mostly try to get the student to show what kind of strategies and types of learning they try to implement in their studies. All the learning categories are number values in likert-scales (values from 1 to 5). Points, attitude and age are integer values. The survey was completed in Finnish."


## 2. Graphical overview of the data
ggpairs(analysisData, lower = list(combo = wrap("facethist", bins = 20)))

### Correlation between variables

"In out pairs plot we can see that the correlations between the variables are quite low. Only a real significant correlation can be found between attitude and points (0,44) and deep learning strategies and surface level strategies (the correlation between the two strategies is negative)." 

### Distributions of variances
"Almost all of the variances of the variables are noramlly distributed.Tge onyl exception is age, which is explained due to the fact that the participants of the survey are students, who are young and mostly the same age."

### Distribution of residuals 
"In most of the cases we cannot see a clear linear pattern in the residuals between two variables. Some show a clear pattern, like attitude and surface learning strategies, where the residuals are skewed towards negative values."

## 3. Own linear regression model & 4. Summary of the fitted model

myRegressionModel <- lm(Points ~ Attitude + stra + surf, data = analysisData)
summary(myRegressionModel)

"Here i created a linear regression model where the students attitude, strategic learning techniques and surface techniques try to explain the students achievement levels in the final exam of the course. In this first model, we can see that surface and stategic learning do not have any significance on the students outcomes in the course test. Their attitude towards the study of statistics, however, proves to be very significant."


secondModel <- lm(Points ~ Attitude, data = analysisData)
summary(secondModel)

"In the second model, we can see that the students attitudes have an extremly significant causal relation to the points that they receive in the final exam. This means that the likelyhood to get a dataset this deviant is less than one percent. In this model one point in attitude increased the points that a student got in the exam by 0.35. The multiple R-squared means that the variance of the points in the test can be explained by about 19 percent by the differences in the attitudes of the students."

## 5. Diagnostic plots

par(mfrow = c(2,2))
plot(x=secondModel, which= c(1,2,5))

"In the assumptions of the model, we assume the variables are normally distributed and that their variance is constant. From the residuals vs fitted, we can see that there seems to be no clear pattern in the distribution of the variables and thefore we can conclude that the model is quite linear. Also the variance is seems to be quite constant as the datapoints dont seem to stray too much from the mean. The  In the normalQQ- plot we can see that our data pretty much follows the line. This means that the data is normally distributed. In the residuals and leverage plot we see that there arent really any outliers that have a big leverage on the rest of the data. The data is bit skewed down, but not significantly."
